# Generated by Django 5.0.2 on 2024-04-28 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_user_result_user_text_alter_user_result_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('plan_description', models.TextField()),
                ('plan_pricing', models.DecimalField(decimal_places=5, max_digits=5)),
                ('discount', models.CharField(max_length=10)),
                ('benefit1', models.CharField(max_length=20)),
                ('benefit2', models.CharField(max_length=20)),
                ('benefit3', models.CharField(max_length=20)),
                ('benefit4', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
