# Generated by Django 5.0.2 on 2024-05-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_remove_plans_benefit3_remove_plans_benefit4'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_image',
            field=models.ImageField(null=True, upload_to='plan_images/'),
        ),
    ]
