# Generated by Django 5.0.2 on 2024-05-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
